"""
GlobalPartners — Alltown Fresh Business Insights Dashboard
Home / Overview page.

Run:
    cd dashboard
    pip install -r requirements.txt
    AWS_PROFILE=globalpartners streamlit run app.py
"""

import streamlit as st
import plotly.express as px
import plotly.graph_objects as go

from lib.data import get_table, query_large

st.set_page_config(
    page_title="GlobalPartners BI — Alltown Fresh",
    page_icon="🍴",
    layout="wide",
)

# ─── Header ───
st.title("GlobalPartners — Alltown Fresh Business Insights")
st.caption(
    "End-to-end data pipeline: RDS SQL Server → S3 Delta Lake (Bronze / Silver / "
    "Gold) → this dashboard. Use the left sidebar to navigate the 7 metric areas."
)

# ─── Top-line KPIs from Loyalty table + Upsell summary ───
st.subheader("Business at a glance")

loyalty = get_table("gold_loyalty_comparison")
upsell = get_table("gold_upsell_summary").iloc[0]

total_revenue = float(loyalty["total_revenue"].sum())
total_orders = int(loyalty["order_count"].sum())
total_customers = int(loyalty.loc[loyalty["segment"] != "Anonymous", "customer_count"].sum())
loyalty_customers = int(loyalty.loc[loyalty["segment"] == "Loyalty", "customer_count"].iloc[0])
loyalty_pct = (loyalty_customers / total_customers * 100) if total_customers else 0

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Total Revenue",   f"${total_revenue:,.0f}")
col2.metric("Total Orders",    f"{total_orders:,}")
col3.metric("Unique Customers", f"{total_customers:,}")
col4.metric("Loyalty Share",   f"{loyalty_pct:.1f}%",
            help="Loyalty customers as % of known customers")
col5.metric("Upsell Share of Rev", f"{float(upsell['upsell_share_of_revenue_pct']):.2f}%",
            help="Paid-option revenue as % of total order revenue")

st.divider()

# ─── Hero chart: CLV daily evolution by tier (aggregated) ───
st.subheader("CLV daily evolution by tier (PRIMARY metric)")
st.caption(
    "Median cumulative spend per customer, plotted daily and split by "
    "CLV tier (High / Medium / Low, recomputed each day). This is the "
    "hero metric for the assessment — it shows how customer lifetime value "
    "evolves day by day across the entire customer base."
)

clv_agg = query_large("""
    SELECT
        date_key,
        clv_tier,
        approx_quantile(cumulative_spend, 0.5) AS median_spend,
        COUNT(*) AS cust_count
    FROM gold_clv_snapshot
    WHERE clv_tier IN ('High', 'Medium', 'Low')
    GROUP BY date_key, clv_tier
    ORDER BY date_key, clv_tier
""")

fig_clv = px.line(
    clv_agg,
    x="date_key",
    y="median_spend",
    color="clv_tier",
    color_discrete_map={"High": "#2ca02c", "Medium": "#1f77b4", "Low": "#d62728"},
    labels={"date_key": "Date", "median_spend": "Median Cumulative Spend ($)", "clv_tier": "Tier"},
    title="Median cumulative spend per customer, by CLV tier, over time",
)
fig_clv.update_layout(hovermode="x unified")
st.plotly_chart(fig_clv, use_container_width=True)

# ─── Quick tier-share donut ───
latest = clv_agg.sort_values("date_key").groupby("clv_tier", as_index=False).tail(1)
col_a, col_b = st.columns([1, 2])
with col_a:
    st.subheader("Customer count by tier (latest)")
    donut = go.Figure(data=[
        go.Pie(
            labels=latest["clv_tier"],
            values=latest["cust_count"],
            hole=0.55,
            marker=dict(colors=["#2ca02c", "#1f77b4", "#d62728"]),
        )
    ])
    donut.update_layout(showlegend=True, height=360, margin=dict(t=20, b=20))
    st.plotly_chart(donut, use_container_width=True)

with col_b:
    st.subheader("Navigate to metrics")
    st.markdown("""
    **Left sidebar**:
    - **1 — CLV Snapshot**: daily CLV evolution, individual trajectories (PRIMARY)
    - **2 — RFM Segments**: Recency / Frequency / Monetary customer segmentation
    - **3 — Churn Indicators**: at-risk / inactive customer detection
    - **4 — Sales Trends**: daily / weekly / monthly revenue rollups
    - **5 — Loyalty Comparison**: loyalty vs non-loyalty vs anonymous
    - **6 — Location Performance**: 27 restaurants ranked
    - **7 — Upsell Analysis**: paid vs free options (the discount pivot)
    """)

st.divider()
st.caption(
    "Data source: `s3://globalpartners-aws/gold/` Delta Lake tables. "
    "Generated by 14 AWS Glue jobs on a daily schedule. "
    "See session reports in the project root for pipeline details."
)
